### ISSUE TITLE
Requirements.txt and models.h5 missing

### ISSUE THREAD

**Issue by shamaunalam** [akshaybahadur21/Socratic#2]
Hey!! this is awesome project, If you will provide requirements.txt and models.h5, for starters, it'd be great. Currently I'm unable to run the project because of missing modules.

**Comment by akshaybahadur21** [comment]
@shamaunalam - You can find the details of the model here
Code : https://github.com/akshaybahadur21/MathEw

**Comment by shamaunalam** [comment]
Thank you very much for responding
